FROM node:8.9

# working directory setup

RUN mkdir -p /var/app
WORKDIR /var/app

# get the app into the image
COPY . /var/app

# how to npm install ???
RUN npm install

# run the app when the container starts
CMD ["node", "src/index.js"]
